### ISSUE TITLE
Order might get rejected because of fee

### ISSUE THREAD

**Issue by vkgnosis** [gnosis/gp-v2-trading-bot#22]
I think this is what happened in some trading bot runs that failed because the order got rejected because of insufficient fee like https://logs.gnosisdev.com/goto/5c0850bae0139dda90896a9c4a11739a .

The problem is that:
* the bot has an amount of sell_token based on which it queries the fee,
* it subtracts the fee_amount from the sell_amount to create the order
* the resulting order has a smaller sell amount than what we originally queried the fee for so the minimum fee could be higher

From api perspective it is a little annoying that there is no way to get the actual "maximum sell amount" you can set taking the fee into account. We would have to do some kind of estimation like using more fee or using only half the initial balance for the sell amount so that the fee is very likely to fit into the other half.

**Comment by fleupold** [comment]
It looks like the same issue is affecting our frontend (cc @anxolin)

When querying the price of 0.1 WETH we ask what fee we need to pay for a 0.1 WETH sell order, but then only place the order for a significantly smaller amount (<50%):

![117636119-ca20a780-b180-11eb-9d00-a747e8bc34e5](https://user-images.githubusercontent.com/1200333/117636349-00f6bd80-b181-11eb-8c0d-4a6815af666d.png)

Since the backend now estimates different fees for different amounts (as the route may change and therefore the cost of baseline execution may be different for 1ETH vs 10ETH trades), it may reject the order due to insufficient fee:

![image](https://user-images.githubusercontent.com/1200333/117636062-bb39f500-b180-11eb-997f-c5422b23b620.png)

**Comment by vkgnosis** [comment]
We can now use the new feeAndQuote endpoint to find the fee and sell amount based on a total available amount of a sell token.

**Comment by anxolin** [comment]
Not sure if the link should show me the log, but it didn't

![image](https://user-images.githubusercontent.com/2352112/123081288-19afef80-d41e-11eb-9d9e-84fb35d13099.png)

I agree is not intuitive, and your new endpoint should be easier for clients to use.

I haven't fully understand the issue though.
- If we query the fee `F`, for amount `A`
- And then submit the order with Sell amount, `S = A - F`
- I would think our Fee is always good, since:
   - `S < A` (since `S + F = A, and F > 0)
   - `Fee(X) >= Fee(Y), when X>Y

**Comment by vkgnosis** [comment]
Related https://github.com/gnosis/gp-v2-services/issues/776 .

Right now this is not an issue for the reason described in that issue. It was an issue before because if the amount changes then the fee could go lower or higher, we don't know so there is no guarantee that the fee for one amount is valid also for another amount.

**Comment by fleupold** [comment]
`Fee(X) >= Fee(Y), when X>Y`

This assumption is not necessarily true. Imagine a case where there is a small reserve two hop route which offers a better price for small amounts (but since it has two hops has a larger fee), but for a large trade it has too much price impact. Therefore, it's better to use the potentially big reserve direct pool for the large trade.

Maybe this example would break down if we had a "perfect" baseline solver that can break trades into multiple sub-routes and end up using both pools even for the large route, but right now the route can change quite discretely.
